=== R0-B1N/uni-web-development/24-12-01 XML final/24-12-01 XML Aufgaben final/adressbuch.dtd
<!ELEMENT adressbuch (adresse*)>

<!ELEMENT adresse ((firma | person), strasse, ort)>

<!ELEMENT firma (firmenname)>
<!ELEMENT person (anrede?, vorname+, nachname)>

<!ELEMENT strasse (#PCDATA)>
<!ELEMENT ort (#PCDATA)>
<!ELEMENT firmenname (#PCDATA)>
<!ELEMENT anrede (#PCDATA)>
<!ELEMENT vorname (#PCDATA)>
<!ELEMENT nachname (#PCDATA)>

=== R0-B1N/uni-web-development/24-12-01 XML final/24-12-01 XML Aufgaben final/Aufgabe1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE adressbuch SYSTEM "C:\Users\nikla\OneDrive\Desktop\XML\Adresse\adressbuch.dtd">

<adressbuch>
	<adresse>
		<person>
			<anrede>Herr</anrede>
			<vorname>Max</vorname>
			<nachname>Mustermann</nachname>
		</person>
		<strasse>Musterstr. 15</strasse>
		<ort>12345 Musterstadt</ort>
	</adresse>
	
	<adresse>
		<firma>
			<firmenname>Musterautomation</firmenname>
		</firma>
		<strasse>Musterstr. 56</strasse>
		<ort>12345 Musterstadt</ort>
	</adresse>
</adressbuch>
