=== R0-B1N/uni-web-development/24-12-01 XML final/24-12-01 XML Aufgaben final/Aufgabe2.dtd
<!ELEMENT pets (dogs, cats)>

<!ELEMENT dogs (dog*)>
<!ELEMENT cats (cat*)>

<!ELEMENT dog (color)>
<!ATTLIST dog breed CDATA #REQUIRED>

<!ELEMENT cat (color)>
<!ATTLIST cat breed CDATA #REQUIRED>

<!ELEMENT color (#PCDATA)>

=== R0-B1N/uni-web-development/24-12-01 XML final/24-12-01 XML Aufgaben final/Pets/pets.xml
<?xml version="1.0"?>
<!DOCTYPE pets SYSTEM "../Aufgabe2.dtd">
<pets>
	<dogs>
		<dog breed="Labrador">
			<color>Black</color>
		</dog>
		<dog breed="Labrador">
			<color>Golden</color>
		</dog>
		<dog breed="Irish Setter">
			<color>Brown</color>
		</dog>
	</dogs>
	<cats>
		<cat breed="Siamese">
			<color>Cream</color>
		</cat>
		<cat breed="Burmese">
			<color>Grey</color>
		</cat>
		<cat breed="Tortoiseshell">
			<color>Brown</color>
		</cat>
	</cats>
</pets>
